#!/bin/bash

echo "THIS SCRIPT HAS BEEN DEPRECATED"
echo "if you want to be guided through the release of a new guides version you can run npx ember-learn-release-tool"
echo "source code for the tool is available here https://github.com/ember-learn/ember-learn-release-tool"
